### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by shiltemann** [shiltemann/phinch-galaxy-ie#1]
My attempt at making a Galaxy Interactive Environment for Phinch (and just an FYI to @bgruening @erasche)

This is just an issue to keep track of some TODOs for myself:

TODOs:
- [x] basic functionality
- [x] fix export to image function (image generation fails now) (stop using SimpleHTTPServer, doesn't implement POST)
- [x] image export should save to galaxy history
- [x] disable obsolete buttons (make share, browse file etc)
- [x] export for filtered biom format -> galaxy history
  - [x] nicer notification of success/failure of export than alert (reuse image export dialogue box)
- [x] fix test for biom format in xml 
- [x] page not resizing for larger images (e.g. sankey diagram)
  - [x] dynamic resize? (now just hardcoded page to be huge :/)
- [x] fix docker timeout, using keep_alive function in js
  - [x] alert users of failed export due to docker being stopped (e.g. if it remained open in a background tab, keep alive will only keep pinging if it is the main tab of the window in chrome)
- [x] docker image -> DockerHub

**Comment by bgruening** [comment]
Awesome!!!! I had some initial JS problems ins the past and created a PR or issue. Seems this is solved now. Let me also point the Phinch developers to this repo, they seemed to be interested in this work!

**Comment by shiltemann** [comment]
Yup I saw, they haven't merged your PR in yet,  but your fix worked for me, so for now I apply it manually in the Dockerfile, but once they merge it I can remove that.

**Comment by hexylena** [comment]
Ahh this is great! Excellent work @shiltemann, can't wait to see it in Galaxy.

**Comment by shiltemann** [comment]
ok, I finished most of the things on my list, and it seems to be working pretty well for me, so if either of you would care to have a look and test this for me? :) Then I will ask Holly to have a look after and check if all the functionality is there and working as intended.

One thing I'm not really thrilled about is that I've had to hardcode the GIE window height to be 5000 pixels, because it wasn't resizing with the changing page sizes, but as I didn't really see an easy way to fix this I just hardcoded it for now, it should at least be big enough unless you have a truly unreasonable number of samples in your file..

thanks, and please let me know if you have any questions/comments/suggestions etc :)

**Comment by bgruening** [comment]
Saskia I will look at this tomorrow. Just pulling everything for my train-offline work :)
What do you think about including it in: https://github.com/bgruening/galaxy-metagenomics
I need to update this image but it would be an easy way to to give it to Holly.

**Comment by shiltemann** [comment]
ah good idea, would be happy to add it to that image :)

**Comment by bgruening** [comment]
My plan is to merge https://github.com/bgruening/docker-galaxy-stable/tree/more_travis in the next days. This will become :16.01 and I will update the metadata flavour. So hopefully this is done in the next 2 days. Let me know if this is ok for you.

This looks awesome Saskia!

**Comment by shiltemann** [comment]
sure, no problem (and no hurry), just keep me posted :)

**Comment by bgruening** [comment]
Ah so long ago ... I have serious problems with Dockerhub and migrated a few images to `quay.io`, which is so much better!!!

So here we go:
`https://github.com/bgruening/galaxy-metagenomics`
which is right now building and can be started with:
`docker run --rm -p 8080:80 -it -p 8800:8800 -v`pwd`/foo/:/export/ --privileged=true quay.io/bgruening/galaxy-metagenomics`

Locally its running and I can the the visualisation! So great! Very nice work @shiltemann!
I was able to crash Phinch, but this is probably a bug in Phinch.

So let me know if it's working for you.

**Comment by shiltemann** [comment]
ah cool, thanks Bjorn! :)

So first of all I ran into an issue with all IEs, related to btrfs; docker wasn't running in the container and I had to do a 

rm -R /export/var/lib/docker/btrfs

and start docker service again before IEs would work at all (whether or not I actually exported the export folder). I saw you had a rather large issue thread on this already, but I still run into it with this image.

After that Phinch seemed to work, except it always times out after one minute, this seems to be because the tcpdump program (which I use to determine how long it has been since last user request and stop if this was more than 10 minutes ago) doesn't appear to work inside the Phinch docker, which appears to be a known problem ( https://github.com/docker/docker/issues/14140) (do you get this too?)

I will see if I can change my docker image to fix this 

Also, how did you crash Phinch? I'll have a quick look to see if it is anything I can fix easily :)

Thanks again!

**Comment by bgruening** [comment]
> So first of all I ran into an issue with all IEs, related to btrfs; docker wasn't running in the container and I had to do a
> rm -R /export/var/lib/docker/btrfs
> and start docker service again before IEs would work at all (whether or not I actually exported the export folder). I saw you had a rather large issue thread on this already, but I still run into it with this image.

Are you using btrfs as your backend in Docker? I don't get why the daemon is not starting properly during container start.

> Also, how did you crash Phinch? I'll have a quick look to see if it is anything I can fix easily :)

This could also be an result of the timeout, true. I was not able to reproduce the crash. Maybe this was a coincident with the timeout. Why are you not using the monitor_traffic script from Jupyter/IPython, this should work without tcpdump.

**Comment by shiltemann** [comment]
> Are you using btrfs as your backend in Docker? I don't get why the daemon is not starting properly during container start.

No I am not.. 

> Why are you not using the monitor_traffic script from Jupyter/IPython, this should work without tcpdump.

I made a custom script because the connection on the port always closes within a minute orso of the last HTTP request.. so you can't distinguish between the case where the user really navigated away from the Phinch IE or just didn't do anything that required a server request for a minute (and a lot of actions are done client side so they could still have been busy using Phinch and the netstat script would not detect a connection on the port and close Phinch prematurely). So I wanted to only timeout after ten minutes of inactivity.. (It's still not the best solution, it could now still close the Phinch container prematurely, i.e. even if your Phinch window is still open, only now it's after a longer time of inactivity..).  So if you know a better way I'm all ears! :)

I at least added some dialogue windows to let users know if the container had stopped when they try to perform a server request (like image/biom export), so maybe your crash was another server action that I didn't make a notification dialogue for yet.. It would be best of course if we could shut down the container only if the user really closed the IE window, but the netstat script wasn't doing that for me.. and this solution was at least somewhat better..

**Comment by bgruening** [comment]
@shiltemann have a look at this one: https://github.com/galaxyproject/galaxy/blob/dev/config/plugins/interactive_environments/jupyter/templates/jupyter.mako#L52

It pings your container as long as the site is open. With this in place we can be sure to get notification inside of the container as long as the site is open.

I don't get this btrfs error. I don't use btrfs et all :(

**Comment by shiltemann** [comment]
ah great! tried a lot of keep_alive settings in a bunch of different places, but none seemed to work :P ..but this sounds good, will try it and let you know, thanks!

> I don't get this btrfs error. I don't use btrfs et all :(

I know, it's a weird one, had the same at home with your regular galaxy docker, don't use btrfs anywhere either..

**Comment by shiltemann** [comment]
ok, the timeout thing is fixed, thanks for link :)

I just have a problem with exporting to the Galaxy history now. I'm getting: 

"Exception: Could not connect to a galaxy instance. Please contact your SysAdmin for help with this error" 

but I get the same error with the IPython and Rstudio notebooks, so thinking it may be something more general? ..should I be starting the container differently orso?

**Comment by bgruening** [comment]
Can you try to not use localhost:8080 but your hostname?

**Comment by shiltemann** [comment]
ahh yep, that was it, thanks :)

Everything seems to work fine, and monitor traffic is a lot better now :)  ..I updated my dockerhub image, but also made some changes to GIE folder so if you rebuild the metagenomics docker image so it does a fresh pull from this repo it should all work out of the box as far as i can tell :)

let me know if you still manage to crash phinch ;P

and btw, FWIW: at home I did not get the btrfs error (while I did with the general galaxy docker couple of weeks ago).. so who knows..

**Comment by bgruening** [comment]
Nice! I triggered a build just now. So in 1h latest everything is up-to-date!
Thanks Saskia!

**Comment by bgruening** [comment]
@shiltemann what do we need as next step?
Is this good enough to get it into Galaxy main?

**Comment by shiltemann** [comment]
I think so yes. If you didn't run into any issues when testing this or have any other comments?

Lemme just add a tag to the dockerhub image I guess so I don't overwrite it if I ever accidentally push without a tag :)

**Comment by bgruening** [comment]
I have not seen any issues so far :)
Do you want to inform the phinch developers? Looking forward to the PR!

**Comment by shiltemann** [comment]
ok, great :) I will update Holly and make a PR this week, thanks for all your help!!
